backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "My blog"
    folder: "src/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Hidden", name: "hidden", widget: "boolean", default: false}
      - {label: "Topic", name: "topic", widget: "string", required: false}
      - {label: "Path", name: "path", widget: "string", default: "/"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      